apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot-concourse-sample
  name: spring-boot-concourse-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-concourse-sample
  template:
    metadata:
      labels:
        app: spring-boot-concourse-sample
    spec:
      containers:
      - image: "malston/spring-boot-concourse-sample:__IMAGE_TAG__"
        name: spring-boot-concourse-sample
