# Enables the kubernetes resource, which is a third-party resource available
# at https://github.com/zlabjp/kubernetes-resource
resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.17"

resources:
  # This resource is the repository that contains the application source code
  # and configuration of the pipeline tasks.
  - name: code-repo
    type: git
    source:
      branch: master
      uri: https://github.com/alexbrand/spring-boot-concourse-sample.git

  # This resource is the container image that is pushed to a remote registry.
  - name: container-image
    type: registry-image
    source:
      repository: ((docker-hub-account))/spring-boot-concourse-sample
      username: ((docker-hub-user))
      password: ((docker-hub-pass))

  # This resource is the target Kubernetes cluster for deployment.
  - name: kubernetes-cluster
    type: kubernetes
    source:
      server: ((kubernetes-api-endpoint))
      token: ((kubernetes-service-account-token))
      certificate_authority: ((kubernetes-certificate-authority))

jobs:
    # This job checks out the code repo, builds the container image, and pushes
    # the image to a remote registry.
  - name: build-push-image
    plan:
    - get: code-repo
      trigger: true
    - task: build-container
      privileged: true
      file: code-repo/ci/tasks/build-container.yml
    - put: container-image
      params:
        additional_tags: code-repo/.git/short_ref
        image: image/image.tar

    # This job renders the deployment manifests and applies them against the
    # target Kubernetes cluster.
  - name: deploy-kubernetes
    plan:
    - get: container-image
      passed: ["build-push-image"]
      trigger: true
    - get: code-repo
      passed: ["build-push-image"]
      trigger: true
    - task: render-manifests
      file: code-repo/ci/tasks/render-manifests.yml
    - put: kubernetes-cluster
      params:
        kubectl: apply -f rendered-manifests/